### PR TITLE
Added some css styling for the meta pages

### PR DESCRIPTION
**Pull request by k-cleary**
Made them more readable. Overwrote the stylish fonts -_- (I think we should revisit this... maybe.... I think they look really plain now)

### CODE REVIEW

**Comment by JesseTG** [comment]
You forgot the Copyright policy.  Also, Copyright policy shouldn't be in our copyright declaration at the bottom, it should just be a separate link in the footer.

**Comment by k-cleary** [comment]
I see copyright policy in the changed files section... Also, I think it's less cluttered to just link the copyright declaration to the copyright page -- I feel like it would be redundant to have another link in the footer nav for the copyright page

**Comment by JesseTG** [comment]
The fonts in the copyright policy aren't changed.

Also, the copyright policy doesn't mean what you think it does.  The copyright policy says "if someone is violating your copyright (pretending to be you, posting your stuff without your permission, etc.), this is what you can do to resolve it".  The Copyright declaration says "As of 2016, Mixxy belongs to www.purple".

**Comment by k-cleary** [comment]
asjdksadlksaldksalkdla ok sorted the copyright issue. The fonts should totally be working (they should have been fixed from the previous commit)

**Comment by JesseTG** [comment]
Also, like I said, the fonts themselves are nice!  There's probably a bunch of other places they'll fit nicely.  It's just that the three important meta pages need to be less "Wow!  Fun!" and more "Take me seriously."

**Comment by JesseTG** [comment]
Also, :+1:.  Merge at will.

**Pull request merged**
