### PR TITLE
Team contribution guidelines

### PR DESCRIPTION
**Pull request by JesseTG**
So, we talked about all of this in our meeting today.  Here it is codified, plus some small additions that came to mind later on.  Thoughts?  We can always change or clarify these rules later, as long as we continue to follow them.

Anything related to actual code will probably be added later, or specified through a static analyzer (which I'll set up as part of the Maven pipeline).

### CODE REVIEW

**Comment by Bsabz** [comment]
:+1:

**Comment by JesseTG** [comment]
@k-cleary @cristianomj Thoughts?

**Comment by k-cleary** [comment]
:+1:

**Comment by JesseTG** [comment]
OK, it's settled.  If anyone wants to propose a change later because one of these rules turns out to not be so great, I'll happily hear it.  But for now, this is our gospel.

**Pull request merged**
