### PR TITLE
Cris/apikeys

### PR DESCRIPTION
**Pull request by cristianomj**
This should fix the problems with the callback URIs. It also uses the encrypted keys.

### CODE REVIEW

**Comment by JesseTG** [comment]
You made sure to change the secrets from what was committed, right?  If so, go ahead and merge (but send @Bsabz the changed `auth.properties` on Slack, as he's temporarily constrained to Windows which `git-crypt` does not support)

**Comment by cristianomj** [comment]
Yeah I made sure to restore all keys. I'll merge soon, just adding one little thing.

**Comment by JesseTG** [comment]
All right, awesome.  Good work.  :+1:

**Comment by Bsabz** [comment]
Looks good :+1:
@cristianomj please remember to send me the updated auth.properties **before** u merge this

**Pull request merged**
