### PR TITLE
Proofread the SRS (round one)

### LINKED ISSUE #28: Proofread all writing
I'll work on getting the text and formatting to be more consistent.

### PR DESCRIPTION
**Pull request by JesseTG**
Fix #28

### CODE REVIEW

**Comment by JesseTG** [comment]
Thoughts on my updates to the text?

**Comment by Bsabz** [comment]
Looks good so far, btw shouldn't we index the Use Cases also like : "2.1, 2.2, 2.3, ....2.13..." ?

**Comment by JesseTG** [comment]
I dunno.  Should we?  Doesn't seem necessary to me, given that we can generate a TOC.

**Comment by JesseTG** [comment]
Executive override, deadline approaching.

**Pull request merged**
